image: skiafgitpodacr.azurecr.io/auth-service-template:1115
tasks:
  - before: git clone https://$repoid:$repopw@dev.azure.com/SKI-DT-Infra/skiaf2.0/_git/auth-service
    init: cd auth-service
    command: mvn spring-boot:run

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 8888
    onOpen: open-preview
